### PR TITLE
Add support for @JsonView

### PR DESCRIPTION
**Pull request by ghost**
This PR addresses Issue #33 by updating the HALBeanSerializer to use the _filteredProps when it is not null and there is an active JSON View. The _filteredProps is further filtered since the default Bean Serializer enforces the JSONView in the serializeAsField, which is not used for the serialization of the Link/Embedded props themselves.

### CODE REVIEW

**Comment by arucard21** [comment]
I took a quick look and, while I'm not too familiar with the Jackson databind code, it seems pretty straightforward and looks good. I do have a suggestion for some more tests, which should be easy enough to add with the setup that you already have. It might be good to add the following:
* Test that deserializing also goes well with JsonView using `readerWithView()`
* Test that serializing goes well when the Java object has JsonView but you don't use it, e.g. by using `writerFor()`
* Test that deserializing goes well when the Java object has JsonView but you don't use it, e.g. by using `readerFor()`

**Comment by ghost** [comment]
I have added the additional tests. The Deserialization tests confirms there are no existing issues wrt JSONViews.

The props in the _filteredProps are wrapped in [FilteredBeanPropertyWriter](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/impl/FilteredBeanPropertyWriter.java), which makes the decision whether to write the property or not. So just using the _filteredProps was not enough as the HALBeanSerializer doesn't call the FilteredBeanPropertyWriter.serializeAsXXXX method on the prop for Link/Embedded props, but rather call the writeXXXX methods directly.

The additional filtering of _filteredProps is a little over zealous as it handles not just the Link/Embedded props, but all props of the Resource. I don't see this as a big deal and could even improve some performance as all the unnecessary FilteredBeanPropertyWriter.serializeAsXXX calls are skipped.

**Review by arucard21 — APPROVED** [review]
Looks good to me and the tests seem to ensure that everything works as intended. 

@langecode Are you okay with me merging this?

**Comment by langecode** [comment]
Thx for the contribution @timothy-volvo and for the review @arucard21 - I have merged it will create a new release soon.

**Pull request merged**
