### PR TITLE
Add curies support as a continuation of Jim Hooker PR #6

### PR DESCRIPTION
**Pull request by AllanHoejgaardJensen**
This is the suggested additions to the original PR #6 @jimhooker2002 where tests and some documentation added.

### CODE REVIEW

**Comment by langecode** [comment]
I have reworked the deserialization somewhat... Basically now every link relation is resolved into the complete uri (if templated by a curie).. This allows for incoming documents to have defined other curie prefixes as well as incoming documents which have no curies but full link relation names.

Probably needs a bit more clean up...

**Review by AllanHoejgaardJensen — COMMENTED** [review]
It is clearer using prefix....

**Comment by langecode** [comment]
The deserialization you mean? Yes it was more simple before but the semantic was somewhat wrong. Note the new test cases. Since the curies are basically a short notation for the relations we should be able to parse an incoming document where no curies are defined but the relations are written in full. We should also be able to parse an incoming document where the curie prefixes are chosen to be other than the ones in the POJO annotations. That is why the deserialization now resolves the curies of the POJO and the curies of the incoming document before trying to match incoming links against POJO properties.

**Comment by langecode** [comment]
I have restructured the deserialization some more to make it more clean and added some more documentations.

One final thing I am wondering is whether the `@Curie` annotation should take the href in form of a `HALLink` instead of a `String`. This would match the output better as the curies really are defined using `HALLink` instances - however it would make the definition part more complex. I did not change anything as parsing the string based href detecting whether it is templated or not is probably a lot more readable.

**Review by langecode — APPROVED** [review]
Looks good to me now going to merge soon.

**Comment by langecode** [comment]
I will be merging this. Thanks to @jimhooker2002 for the initial work on this.

**Pull request merged**
